scholarly:
  - arxiv.org
  - doi.org
  - openreview.net
  - aclanthology.org
  - acm.org
  - ieee.org
  - nature.com
  - science.org
  - springer.com
  - elsevier.com
  - oxfordacademic.com
  - cell.com
  - aaai.org

guideline:
  - joschu.net
  - michaelnielsen.org
  - neelnanda.io
  - gwern.net
  - alignmentforum.org
  - thoughtforms.life
  - letters.lossfunk.com
  - colah.github.io
  - 01.me
  - lesswrong.com

portal:
  - researchgate.net
  - semanticscholar.org
  - scholar.google.com
  - datanorth.ai
  - generativeai.pub
  - haofei.vip
  - news.ycombinator.com
