version: 2

absolute_metrics:
  scaled:
    - actionability_score
    - rag_fidelity_score
    - question_quality_score
    - persona_compliance_score
    - stage_awareness_score
    - tone_constructive_score
    - citation_relevance_score
    - source_fit_score
    - citation_quality_score
  binary:
    - tool_routing
    - citation_presence
    - citation_validity
    - fallback_robustness
    - asks_questions
    - constraint_handling
    - evidence_integrity

weights:
  actionability_score: 1.0
  rag_fidelity_score: 1.2
  question_quality_score: 0.8
  persona_compliance_score: 1.0
  stage_awareness_score: 1.0
  tone_constructive_score: 0.8
  citation_relevance_score: 0.6
  source_fit_score: 0.6
  citation_quality_score: 0.6
  evidence_integrity: 1.0

pairwise:
  aspects:
    inquiry_quality: 1.0
    persona_adaptation: 1.0
    methodology_critique: 1.0
    plan_completeness: 1.0
    literature_quality: 1.0
    actionability_risks: 1.0
    guideline_adherence: 1.0
